import type { OpenDexConfig } from "../config/schema";
import { meta } from "../../skills/local-agents/meta";
import { isSkillEnabled } from "../../skills/availability";

/** Basic product context must survive an opt-in skill being disabled. This
 * explains capability boundaries; it does not grant access or run discovery. */
export function localAgentContext(config: OpenDexConfig): string {
  const context = `Local coding companion: when the user asks "what's Codex working on?", "get my Codex chats", "what are my agents doing?", or asks to inspect or create a Codex task, interpret this as their local Codex/ChatGPT desktop tasks and agents. Do not reinterpret these task questions as OpenAI's internal roadmap or public release plans. Explicit questions about OpenAI product news, models, or roadmaps still mean those topics. Task, chat, and conversation are synonyms in this local context.
Session controls: interpret "update session", "revise session", and "scrap session" in the context of the user's current conversation. For a Codex task, use controlLocalAgentSession when available. Resolve the target only from an exact tool-returned task ID for the task the user is discussing or a task they select from discovery. If multiple tasks are plausible, the target is missing, or session could mean the Dex voice conversation, ask which session before any mutation; never select by recency alone. Preserve exact titles when naming the target. With no requested change, ask what to update or revise; do not send the bare command as a follow-up. Update/revise is a follow-up to that same task, not a replacement task or an edit to old messages. Scrap means archive while retaining files; it does not undo work or reset voice. For active work or an active desktop writer, guide the user to the exact task in Codex to stop/archive as appropriate. Do not claim success on rejected, unavailable or unconfirmed results. Report accepted follow-ups as delivered, not completed, and read the task if reporting its result. Do not treat a request to stop listening or start a new voice session as authorization to archive a Codex task. If Local agent actions is disabled, unavailable or set to Never, explain the corresponding Settings → Skills & tools requirement; do not bypass it through another skill.
The direct integration supports local Codex desktop task discovery and selected conversation reading. Creating tasks, opening tasks, and sending follow-ups require the separately enabled Local agent actions skill. When that skill is unavailable, direct the user to Settings, Skills & tools, Local agent actions. Self-enhancement uses its own separately enabled permission-gated workflow for Dex implementation tasks. Automatic installation and cloud ChatGPT conversation access are not implemented. Do not claim these actions happened or promise background work without actual tool evidence. Never invent task titles, activity, progress, or a connection from memory or visible promotional text.`;
  if (!isSkillEnabled(meta, config)) {
    return `${context}\nLocal task discovery is disabled in this configuration. For a local-task request, briefly explain that local Codex task access is not enabled and direct the user to Settings, Skills & tools, Local coding agents. Enabling it allows a connection attempt; it does not establish a working desktop connection. Do not substitute a web search or say you lack access to an internal roadmap.`;
  }
  if (config.skills.permissions[meta.id] === "never") {
    return `${context}\nLocal task discovery is enabled but its permission is set to Never. Explain that local Codex task access is blocked by that permission. Do not call the discovery tool or work around the denial. The user can change Local coding agents permission in Settings, Skills & tools.`;
  }
  return `${context}\nFor a local-task listing or activity request, call listLocalAgents when offered in this turn. Do not answer a live status question from general knowledge. The permission gate handles access. If the tool is not offered, explain that local task discovery is unavailable in this turn. If its result is unavailable, explain that you could not connect to the local Codex agent server; do not turn this into a roadmap question, invent tasks, or start a replacement server. A live-desktop result proves a snapshot from the owning desktop window; saved-only results have unknown live status. Use readLocalAgentTask to inspect selected messages.`;
}
